MODEL:
  architecture:  "classification"
  img_width: 9
  img_height: 9
  in_channel: 10
  patch_size: 3
  embed_dim: 128
  max_time: 60
  num_classes: 20
  num_head: 4
  dim_feedforward: 2048
  num_layers: 8
  dropoutratio: 0.5

TRAIN:
  batch_size: 8
  learning_rate: 0.001
  max_epochs: 300

DATA:
  Pastis24: '/workspace/PASTIS9/'
  train_ratio: 0.7
  val_ratio: 0.15
