MODEL:
  architecture : "finetuning"
  initial_model_path: ""

TRAIN:
  batch_size: 16
  learning_rate: 0.001
  max_epochs: 200

DATA:
  dataset_path: ""
  batch_size: 16
  train_ratio: 0.7
  val_ratio: 0.15


