MODEL:
  architecture:  "segmentation"
  img_width: 24
  img_height: 24
  in_channel: 10
  patch_size: 3
  embed_dim: 128
  max_time: 60
  num_classes: 20
  num_head: 4
  dim_feedforward: 2048
  num_layers: 6
  dropoutratio: 0.2


TRAIN:
  batch_size: 8
  learning_rate: 0.001
  max_epochs: 300
  l2: 0.01



DATA:
  Pastis24: '/workspace/PASTIS24/'
  train_ratio: 0.7
  val_ratio: 0.15
